version: '3'

services:

  flask:
    build:
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    container_name: flask-server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./app:/app

networks:
  some-network:
   driver: bridge
